version: '3'
services:
  flask:
    build:
      context: ./
    ports:
      - "5000:5000"
    depends_on:
      - mysql-db
    environment:
      - MYSQL_HOST=mysql-db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DB=my_database
  mysql-db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=my_database
    ports:
      - "3306:3306"