version: '3'
services:
  flask:
    build:
      context: ./
    ports:
      - "5000:5000"
    depends_on:
      - mysql-db
      - parthub
    environment:
      - MYSQL_HOST=mysql-db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_DB=RAP
  mysql-db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=RAP
    volumes:
      - ./KineticHub/data/Reaction_reactions.sql:/docker-entrypoint-initdb.d/Reaction_reactions.sql
      - ./KineticHub/data/KM_km.sql:/docker-entrypoint-initdb.d/KM_km.sql
      - ./KineticHub/data/KCat_kcat.sql:/docker-entrypoint-initdb.d/KCat_kcat.sql
    ports:
      - "3306:3306"
  parthub:
    image: neo4j:5.11
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/igem2023
      - NEO4J_PLUGINS=["graph-data-science"]
      - NEO4J_dbms_security_procedures_whitelist=gds.*
      - NEO4J_dbms_security_procedures_unrestricted=gds.*
    ports:
      - "7474:7474"
      - "7687:7687"